"""Normative Data Part examples are schema-valid (binding rc1 §8 gate 2).

The examples in ``kiwi/contracts/interop/knp-data-part-examples.json`` are
generated by the Kiwi implementation (``kiwi/scripts/
gen-knp-data-part-examples.mjs``) — full A2A Messages (Text Part optional,
Data Part carrying ``knp_envelope``) plus one Task shape (D5: task results
carry the same KNP domain object in a Data Part).  This test asserts every
example passes the shopping-cli hosted gateway's message-layer parsing and
the KNP envelope schema/digest validation — the normative examples must be
schema-valid on both implementations (rc1 §8 gate 2).
"""

from __future__ import annotations

import json
import unittest
from pathlib import Path

from shopping_cli.a2a.hosted_server import _extract_knp_envelope, _parse_a2a_message
from shopping_cli.a2a.knp import validate_envelope, verify_envelope_digest

EXAMPLES_PATH = (
    Path(__file__).resolve().parents[1]
    / ".."
    / "kiwi"
    / "contracts"
    / "interop"
    / "knp-data-part-examples.json"
)


def _load_examples() -> list[dict]:
    with open(EXAMPLES_PATH, encoding="utf-8") as fh:
        return json.load(fh)["examples"]


class KnpDataPartExamplesTest(unittest.TestCase):
    """binding rc1 §8 gate 2: normative examples are schema-valid."""

    def setUp(self) -> None:
        self.examples = _load_examples()

    def test_all_examples_are_schema_valid(self) -> None:
        self.assertGreaterEqual(len(self.examples), 4)
        for example in self.examples:
            with self.subTest(label=example["label"]):
                if example["kind"] == "message":
                    self._assert_message_valid(example["message"])
                elif example["kind"] == "task":
                    task = example["task"]
                    self.assertEqual(task["status"]["state"], "completed")
                    self._assert_message_valid(task["status"]["message"])
                else:
                    self.fail(f"unknown example kind: {example['kind']}")

    def _assert_message_valid(self, message: dict) -> None:
        # 消息层：hosted gateway 的严格解析（角色/ID/parts 约定）。
        parsed = _parse_a2a_message(message)
        self.assertEqual(parsed["role"], "agent")
        # 恰好一个 Data Part 携带 knp_envelope。
        envelope = _extract_knp_envelope(message)
        # envelope 层：schema 校验 + kiwi 计算的 digest 由 Python 验证。
        validated = validate_envelope(envelope)
        self.assertEqual(validated.message_id, message["messageId"])
        self.assertTrue(verify_envelope_digest(envelope))

    def test_examples_cover_message_and_task_kinds(self) -> None:
        kinds = {example["kind"] for example in self.examples}
        self.assertEqual(kinds, {"message", "task"})


if __name__ == "__main__":
    unittest.main()
